site_name: 'python-app-4'
site_description: 'Main documentation for the python-app-4'
repo_url: https://github.com/monvillanueva-continuous-learning/python-app-4
edit_uri: edit/master/docs

plugins:
  - techdocs-core
  - redirects:
      redirect_maps:
        'index.md': 'overview/what-is-backstage.md'

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.js`
nav:
  - Overview:
      - Getting started: 'docs/index.md'